# Generated by Django 3.0.5 on 2020-06-08 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0002_auto_20200608_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expoilted',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expoilted', to=settings.AUTH_USER_MODEL),
        ),
    ]
