# Generated by Django 3.0.5 on 2020-06-09 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0006_auto_20200608_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to=settings.AUTH_USER_MODEL),
        ),
    ]
